---
exclude_paths:
- ".git/"
- "**.xml"
- "**.yaml"
- "**.yml"
- lib/metadata/linux/test/Packages
- lib/metadata/linux/test/tc_LinuxUtils.rb
- locale/
- spec/
- test/
- tools/
- tmp/
engines:
  brakeman:
    enabled: false
  bundler-audit:
    enabled: false
  csslint:
    enabled: false
  duplication:
    enabled: true
    config:
      languages:
        ruby:
          mass_threshold: 25
          count_threshold: 5
        javascript: 
  eslint:
    enabled: false
    channel: eslint-3
  fixme:
    enabled: false
  markdownlint:
    enabled: false
  rubocop:
    enabled: true
    config: ".rubocop_cc.yml"
    channel: rubocop-0-69
checks:
  method-complexity:
    enabled: true
    config:
      threshold: 8
prepare:
  fetch:
  - url: https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop_base.yml
    path: ".rubocop_base.yml"
  - url: https://raw.githubusercontent.com/ManageIQ/guides/master/.rubocop_cc_base.yml
    path: ".rubocop_cc_base.yml"
ratings:
  paths:
  - Gemfile.lock
  - "**.rake"
  - "**.rb"
